spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://auth:8081/auth}

  cloud:
    gateway:
      routes: []

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

gateway:
  services:
    auth-url: ${AUTH_SERVICE_URL:http://auth:8081}
    budget-url: ${BUDGET_SERVICE_URL:http://budget:8083}
  cors:
    allowed-origins: ${GATEWAY_CORS_ALLOWED_ORIGINS:http://localhost:8080}

logging:
  level:
    pyc.lopatuxin.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO

server:
  port: 8082
